name: Build and Push Docker Image

on:
  push:
    branches:
      - fix-docker-issue

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

    - name: Get OAuth2 access token and login to Docker
      run: |
        ACCESS_TOKEN=$(gcloud auth print-access-token)
        echo "$ACCESS_TOKEN" | docker login -u oauth2accesstoken --password-stdin https://us-central1-docker.pkg.dev
    
    - name: Save GCP token
      run: |
        cat <<EOF > ./gcp_token.json
        ${{ secrets.GCP_SERVICE_ACCOUNT }}
        EOF
    
    - name: Save telegram bot token
      run: |
        cat <<EOF > ./telegram_bot_token.txt
        ${{ secrets.TELEGRAM_BOT_TOKEN }}
        EOF

    - name: Save telegram chat id
      run: |
        cat <<EOF > ./telegram_chat_id.txt
        ${{ secrets.TELEGRAM_CHAT_ID }}
        EOF

    - name: Build and push Docker image
      run: |
        docker build -t us-central1-docker.pkg.dev/singapore-parliament-speeches/singapore-parliament-speeches/image:latest .
        docker push us-central1-docker.pkg.dev/singapore-parliament-speeches/singapore-parliament-speeches/image:latest
